import { Button, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    ta := TouchArea {

    }

    background: gray;

    Rectangle {
        background: yellow;
    }

    VerticalBox {
        AboutSlint {}

        Text {
            text: "Counter: \{root.counter}";
            horizontal-alignment: center;
        }


        HorizontalBox {
            alignment: center;
            Button {
                text: "Increase value";
                clicked => {
                    counter += 1;
                }
            }
        }
    }

    Rectangle {
        width: 5px;
        height: 5px;
        background: ta.pressed ? red : blue;
        x: ta.mouse-x - self.width/2;
        y: ta.mouse-y - self.height/2;
    }
}
