import { Button, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;

    //background: red.mix(blue, sin(animation-tick() * 1turn / 1s));


    ta := TouchArea {
        pointer-event(event) => {
            r.x = self.mouse-x - r.width/2;
            r.y = self.mouse-y - r.height/2;
        }
     }

    VerticalBox {
        AboutSlint {}

        Text {
            text: "Counter: \{root.counter}";
            horizontal-alignment: center;
        }
        t := Text {
            text: "X: " + ta.mouse-x / 1px + ", Y: " + ta.mouse-y / 1px;
        }

        HorizontalBox {
            alignment: center;
            Button {
                text: "Increase value";
                clicked => {
                    counter += 1;
                }
            }
        }
     }

     r := Rectangle {
        width: 5px;
        height: 5px;
        background: red;
     }

}
